Repository fusionjs/fusion-plugin-connected-react-router, pull requests merged in 2018-08, with the labels that each got.

#4 Release v1.0.0
  package.json
Labels: release

#5 Update README with buildkite badge
  README.md
Labels: docs

#7 Update dependencies
  .npmrc
  package.json
  yarn.lock
Labels: greenkeeping
